//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detentions
    {
        public int NumberDetention { get; set; }
        public string DetentionLastName { get; set; }
        public string DetentionFirstName { get; set; }
        public string DetentionSecondName { get; set; }
        public System.DateTime DateOfDetention { get; set; }
        public string PleaceDetention { get; set; }
        public string BaseDetention { get; set; }
        public string Things { get; set; }
        public bool IsNotifiRelatives { get; set; }
        public int Protocol_NumberProtocol { get; set; }
    
        public virtual Protocols Protocols { get; set; }
    }
}
