//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dutys
    {
        public Dutys()
        {
            this.Statements = new HashSet<Statements>();
        }
    
        public int Id { get; set; }
        public int TypeDuty { get; set; }
    
        public virtual EmployeeUsers EmployeeUsers { get; set; }
        public virtual ICollection<Statements> Statements { get; set; }
    }
}
