//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DutyPanelEntities : DbContext
    {
        public DutyPanelEntities()
            : base("name=DutyPanelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AdminUsers> AdminUsers { get; set; }
        public DbSet<Cars> Cars { get; set; }
        public DbSet<Detentions> Detentions { get; set; }
        public DbSet<Drivers> Drivers { get; set; }
        public DbSet<Dutys> Dutys { get; set; }
        public DbSet<EmployeeUsers> EmployeeUsers { get; set; }
        public DbSet<InternetStatements> InternetStatements { get; set; }
        public DbSet<LeavingGroups> LeavingGroups { get; set; }
        public DbSet<Merits> Merits { get; set; }
        public DbSet<OperationalGroups> OperationalGroups { get; set; }
        public DbSet<OperativeWorkers> OperativeWorkers { get; set; }
        public DbSet<OralStatements> OralStatements { get; set; }
        public DbSet<Protocols> Protocols { get; set; }
        public DbSet<Ranks> Ranks { get; set; }
        public DbSet<Statements> Statements { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<WarDogs> WarDogs { get; set; }
        public DbSet<WrittenStatements> WrittenStatements { get; set; }
    }
}
