//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeUsers
    {
        public EmployeeUsers()
        {
            this.Merits = new HashSet<Merits>();
        }
    
        public int Id { get; set; }
        public int Rank_Id { get; set; }
        public int EmployeeNumber { get; set; }
        public System.DateTime DateRegistr { get; set; }
        public System.DateTime DateLastEditedRank { get; set; }
        public string WorkingPhone { get; set; }
        public int PenaltiesCount { get; set; }
        public int NumberServiceCertificate { get; set; }
        public System.DateTime DateIssueServiceCertificate { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Dutys Dutys { get; set; }
        public virtual Ranks Ranks { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Merits> Merits { get; set; }
        public virtual OperativeWorkers OperativeWorkers { get; set; }
    }
}
