//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationalGroups
    {
        public OperationalGroups()
        {
            this.LeavingGroups = new HashSet<LeavingGroups>();
            this.OperativeWorkers = new HashSet<OperativeWorkers>();
        }
    
        public int IdGroup { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual ICollection<LeavingGroups> LeavingGroups { get; set; }
        public virtual ICollection<OperativeWorkers> OperativeWorkers { get; set; }
    }
}
