//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperativeWorkers
    {
        public int Id { get; set; }
        public Nullable<int> Group_IdGroup { get; set; }
        public bool IsHeadOfGroup { get; set; }
        public int NumberServiceWeapon { get; set; }
        public int AccessionNumberHandCuffs { get; set; }
        public bool IsHaveDog { get; set; }
    
        public virtual EmployeeUsers EmployeeUsers { get; set; }
        public virtual OperationalGroups OperationalGroups { get; set; }
        public virtual WarDogs WarDogs { get; set; }
    }
}
