//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OralStatements
    {
        public int NumberStatement { get; set; }
        public string PhoneCaller { get; set; }
        public string AdressCaller { get; set; }
    
        public virtual Statements Statements { get; set; }
    }
}
