//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statements
    {
        public Statements()
        {
            this.LeavingGroups = new HashSet<LeavingGroups>();
        }
    
        public int NumberStatement { get; set; }
        public string DeclarantLastName { get; set; }
        public string DeclarantFirstName { get; set; }
        public string DeclarantSecondName { get; set; }
        public System.DateTime DateStatment { get; set; }
        public System.DateTime DaetIncident { get; set; }
        public string Adress { get; set; }
        public string District { get; set; }
        public string Harm { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public int Duty_Id { get; set; }
    
        public virtual Dutys Dutys { get; set; }
        public virtual InternetStatements InternetStatements { get; set; }
        public virtual ICollection<LeavingGroups> LeavingGroups { get; set; }
        public virtual OralStatements OralStatements { get; set; }
        public virtual WrittenStatements WrittenStatements { get; set; }
    }
}
