//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public int PassportNumber { get; set; }
        public string WhoGivePassport { get; set; }
        public System.DateTime DateGivePassport { get; set; }
        public int SubdivisionPasport { get; set; }
        public string RegistrationAddress { get; set; }
        public string ContactPhone { get; set; }
    
        public virtual AdminUsers AdminUsers { get; set; }
        public virtual EmployeeUsers EmployeeUsers { get; set; }
    }
}
