//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarDogs
    {
        public int IdDog { get; set; }
        public string Name { get; set; }
        public string Breed { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public System.DateTime DateCommencementOfService { get; set; }
        public System.DateTime DateLastInspection { get; set; }
    
        public virtual OperativeWorkers OperativeWorkers { get; set; }
    }
}
