//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrittenStatements
    {
        public int NumberStatement { get; set; }
        public Nullable<int> Leaving_IdLeaving { get; set; }
        public int DeclarantNumberPasport { get; set; }
        public string DeclarantWhoGivePassport { get; set; }
        public int DeclarantSubdivisionPasport { get; set; }
        public System.DateTime DeclarantDateGivePassport { get; set; }
        public string DeclarantRegistrationAddress { get; set; }
        public string DeclarantContactPhone { get; set; }
    
        public virtual LeavingGroups LeavingGroups { get; set; }
        public virtual Statements Statements { get; set; }
    }
}
